name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Analyze commits
      env:
        TOKEN: ${{ secrets.TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number || '' }}
        REPOSITORY: ${{ github.repository }}
      run: |
        source .venv/bin/activate
        python analyze_commits.py

    - name: Generate review comments
      if: github.event_name == 'pull_request'
      env:
        TOKEN: ${{ secrets.TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number || '' }}
        REPOSITORY: ${{ github.repository }}
      run: |
        source .venv/bin/activate
        python generate_review.py
